In [ ]:
import numpy as np

list1=[10,20,30,40,50]
print(type(list1),list1)

nparr=np.array([10,20,30,40,50])
print(type(nparr),nparr)


# np.array is faster than list, You can perform some computation and store val in list
# 1.append()
list2=[]
for val in list1:
    list2.append(val*100)
print(list2)

# 2.comprehension
list2=[val*100 for val in list1]
print(list2)

# 3. map
def fun(val):
    return val*100
for val in map(fun,list1):
    print(val,end=" ")
print(" ")
print(list(map(fun,list1)))
print(list(map(lambda val:val*100,list1)))

# 4. numpy uses ufuncs (universal functions) and performance is fast

nparr=np.array([3,4,5]) # It can only store same dtypes
print(nparr.dtype)
print(nparr*100)
nparr=np.array([3,4.0,5])# implicit upcasting
print(nparr.dtype)

In [ ]:
import numpy as np

a=np.array([[-2,2, 1,2],
            [0, 1,-2,2],
            [1, 1, 0,0],
            [2, 0,-1,0]])

print(sum(a))# sum of cols [1 4 -2 4]
print(np.sum(a))# 7
print(np.sum(a,axis=0))# [1 4 -2 4] col sum
print(np.sum(a,axis=1)) # row sum
print(np.sum(a,axis=1,initial=5)) # add 5

In [ ]:
import numpy as np

a=np.array(10) # This is a 0 dimensional array
print(a) # An array with 1 element 
print(a.ndim) # An array with 0 dimensions 

# Here array can take list or tuple as arg
# Elements should be of same type unlike list
a=np.array([1,2,3,4,5])
b=np.array((1,6,3,4,9))
c=np.array({1,6,3,4,9})
print(a,type(a))
print(b,type(b))
print(c,type(c))

# use dtype property to define datatype explicitly
a=np.array([1,2,3,4,5],dtype='i')
b=np.array((1,6,3,4,9),dtype='f')
c=np.array((1.2,6.7,3.4,4.5,9.6),dtype='i')
d=np.array((1.2,6.7,3.4,4.5,9.6))
print(a,a.dtype)# int32
print(b,b.dtype)# float32
print(c,c.dtype)# int32
print(d,d.dtype)

In [ ]:
import numpy as np

a=np.array([[1,2,3],[4,5,6]])

# Here we can use index 1,2 to access last element
print(a.ndim,a[1][2],a[1,2]) # 2 6 6

# Here ndim property gives 3 dimensions 
# 3D array
b=np.array([[[1,2,3]],[[-1,-2,-3]]])
print(b.ndim) # 3 
print(b) # whole 3D array[[[1 2 3]] [[-1 -2 -3]]]
print(b[1])# second 2D array # [[-1 -2 -3]]
print(b[1][0]) # This is 1D array # [-1 -2 -3]
print(b[1,0,2]) # Element inside 1D array # -3

In [ ]:
import numpy as np

# VisibleDeprecationWarning ndarrays with different lengths or shapes
#a=np.array([[1,2],[3,4,5]])
#print(a[1][2],a.dtype)

# ValueError The requested array has an inhomogeneous shape after 1 dimensions
#a=np.array([[1,2],[3,4,5]],dtype='i')
#print(a[1][2],a.dtype)

# dtype has to be object if different lengths
a=np.array([[1,2],[3,4,5]],dtype=object)
print(a[1][2],a.dtype)
print(a)

In [1]:
import numpy as np

a=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[-1,-2,-3],[-4,-5,-6],[-7,-8,-9]]])

print(a)
print(a.shape) # tuple (2,3,3)
# shape[0] gives total number of 2D arrays
print(a.shape[0]) # 2
# shape[1] gives in each 2D arrays how many 1D arrays
print(a.shape[1]) # 3
# shape[2] gives number of elements in each 1D array
print(a.shape[2]) # 3
print(a.size) # Total number of elements

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[-1 -2 -3]
  [-4 -5 -6]
  [-7 -8 -9]]]
(2, 3, 3)
2
3
3
18


In [2]:
import numpy as np

a=np.array([1,2,3,4,5,6])
print(a.size,len(a)) # total number of elements i.e. 6
print(a.nbytes) # total size of all elements i.e. 24

6 6
24


In [3]:
# np.arange(), np.random.randint(), np.reshape()

import numpy as np

a=np.zeros(10,dtype=int)
print(a)
a=np.arange(20)
print(a)
a=np.arange(1,21)
print(a)
a=np.arange(1,21,2)
print(a)
# shuffled output for testing
a=np.random.permutation(np.arange(10))
print(a)

a=np.random.randint
print(a)# returns generator
#a=np.random.randint? # gives help
#print(a)
a=np.random.randint(10)
print(a,type(a)) # type int
a=np.random.randint(10,50)
print(a,type(a))

[0 0 0 0 0 0 0 0 0 0]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  3  5  7  9 11 13 15 17 19]
[1 8 0 7 3 4 2 9 6 5]
<built-in method randint of numpy.random.mtrand.RandomState object at 0x000002001FF89440>
3 <class 'int'>
40 <class 'int'>


In [5]:
import numpy as np

# 5 random elements in 1D array
#a=np.random.rand(5)
#print(a)

# 2 x 3 elements 2D array
#a=np.random.rand(2,3)
#print(a)

# There are 2 arrays that are 3D
# Each 3D has 4 1D arrays
# each 1D has 5 elements
a=np.random.rand(2,3,4,5)
print(a)
print(a.ndim)

[[[[0.74362266 0.25414749 0.48655164 0.21001174 0.76115529]
   [0.02047092 0.87958857 0.39591696 0.47416059 0.50292498]
   [0.86053033 0.37650924 0.43999333 0.57125045 0.06343311]
   [0.05207884 0.28620876 0.89127012 0.9897671  0.33909931]]

  [[0.93246895 0.23225156 0.08342551 0.47440643 0.93340465]
   [0.73210999 0.3258469  0.92953043 0.58151938 0.91094034]
   [0.77417346 0.33879014 0.43983921 0.62614011 0.18671218]
   [0.38469201 0.49990608 0.95212775 0.3392056  0.6358927 ]]

  [[0.92066242 0.42581923 0.05021684 0.21799539 0.2235794 ]
   [0.88490904 0.81185947 0.10905585 0.91163149 0.25579987]
   [0.39640418 0.59908072 0.35019048 0.26903112 0.67844721]
   [0.79271259 0.08601317 0.76670345 0.61113811 0.96812869]]]


 [[[0.27424031 0.49884724 0.38501917 0.79607373 0.29194674]
   [0.28639556 0.69458528 0.27413178 0.87014472 0.18563124]
   [0.39367865 0.49614617 0.66252052 0.0332424  0.08105207]
   [0.24931702 0.71260418 0.17519824 0.59349115 0.60273818]]

  [[0.69980538 0.27495104 0.83

In [14]:
import numpy as np

# create 100 elements of 4 x 25
a=np.arange(100)
print(a)
a=np.arange(100).reshape(4,25)
print(a)
a=np.arange(100).reshape(2,50)
print(a)

a=np.zeros(5)
print(a)
a=np.ones(5,int)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]
 [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
  49]
 [50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
  74]
 [75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98
  99]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
  48 49]
 [50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
  74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
  98 99]]
[0. 0. 0. 0. 0.]
[1 1 1 1 1]


In [20]:
import numpy as np
a = np.arange(60).reshape(3,4,5) 
print(a)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [24]:
# slicing in numpy A[start:end:step]

import numpy as np

a=np.arange(10)
print(a) # [0 1 2 3 4 5 6 7 8 9]
b=a[5:10] # shallow copy 
print(b) # [5 6 7 8 9]
# for deep copy use a[5:10].copy()
b[0]=100 
print(b) # [100   6   7   8   9]
print(a) # [  0   1   2   3   4 100   6   7   8   9]

# argwhere returns a 2D array
index=np.argwhere(a==100)[0][0]
print(index,type(index))
a[index]=999 # change the element
print(a)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[100   6   7   8   9]
[  0   1   2   3   4 100   6   7   8   9]
5 <class 'numpy.int64'>
[  0   1   2   3   4 999   6   7   8   9]


In [36]:
import numpy as np

# 4 rows 5 col numbers within 10
a=np.round(10*np.random.rand(4,5))
print(a)
# access last row
print(a[3],a[3:],a[3,])
# access last element of last row
print(a[3,4])
# row 1 to 3 and col 2 to 4 
print(a[1:3,2:4])
# to get transpose
#print(a.T)

#from numpy import random
# Generate a 1-D array containing 5 random integers from 0 to 100:
#x=random.randint(100, size=(5))
#print(x)

[[ 1.  9.  3.  5.  5.]
 [ 4.  6.  7.  1.  2.]
 [ 9.  5. 10.  4.  6.]
 [ 3.  1.  0.  5.  5.]]
[3. 1. 0. 5. 5.] [[3. 1. 0. 5. 5.]] [3. 1. 0. 5. 5.]
5.0
[[ 7.  1.]
 [10.  4.]]


In [ ]:
# using sort
import numpy as np

a=np.array([3,1,2,4,5])
a.sort()
print(a)
a=a[::-1]
print(a)

ar=np.array([[4,6,5],[3,2,1],[9,8,7]])
print(ar)
ar.sort(axis=0) # sort on rows
print(ar) 
ar.sort(axis=1) # sort on col
print(ar)

In [ ]:
import numpy as np

# copy vs view
#a[[1,5,8]]
#a[[True,False,True,False,False]]
#a[a<8 & a>4]
#a[a<8 and a>4]

a=np.arange(10)
print(a)
"""
# pick elements 2 6 and 8
#b=a # shallow copy
b=a[[2,6,8,9,1,3]] # deep copy
print(b)
b[0]=100 # b is changed
print(b)
print(a) # a is not changed
"""
b=a[a<5] # create b with elements less than 5
print(b)
# create b with elements less than 8 
# and b with elements more than 3
# use () mandatory & | ~ is used on arrays 
b=a[(a<8)&(a>3)] 
#b=a[(a==3)|(a==9)] 
print(b)

In [ ]:
import numpy as np

# broadcasting A+5 
#a=np.round(10*np.random.rand(2,4))
a=np.arange(8).reshape(2,4)
print(a)
#a=a+5 # 5 will be added to every element
#print(a)
# Here broadcast is happening for 8 elements
# of 2 rows and 4 cols
a=a+(np.arange(8).reshape(2,4))
print(a)

In [ ]:
import numpy as np

a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
b=np.array([[7,8],[9,10],[11,12]])
print(b)
c=np.hstack((a,b))# use tuple for hstack
print(c)
d=np.array([[10,11,12],[13,14,15]])
print(d)
e=np.vstack((a,d))
print(e)

In [ ]:
import pandas as pd

# data munging, cleaning, preprocessing, etc.
print(pd.__version__)

# Series handles 1D arrays
a=pd.Series([3,2,1,4,5],index=['a','b','c','d','e'])
# numpy plays a role in pandas 
print(a.values,type(a.values),type(a))
print(a.index)

#indexes are keys to access values like dict 
print(a['c'])

# we can use slicing to access series # stop value is included in slicing
print(a['a':'d'])

In [ ]:
import pandas as pd

grades_dict={'A':80,'B':70,'C':50}
series_grades=pd.Series(grades_dict)
print(series_grades.values)
print(series_grades.index)
print(grades_dict['A'])

In [ ]:
# series is a sequence of values with associated labels
import pandas as pd
import numpy as np

countries=['india','pakistan','srilanka']
print(pd.Series(countries)) #dtype object

per_pop=[17.5,2.3,0.23]
print(pd.Series(per_pop)) #dtype float64

population=[1234567890,1233456789,123456]
print(pd.Series(population)) #dtype int64

mix_type=['india',17.5,1234567890]
print(pd.Series(mix_type)) #dtype object

#Pandas do not convert data to same type like numpy
print(np.array(mix_type),type(np.array(mix_type)))
# Note: data is parameter and mix_type argument
print(pd.Series(data=mix_type)) 

In [ ]:
#Attribute is a variable bound to object
#Method is a function bound to object
import pandas as pd
pd_val1=pd.Series([10,20,30],index=[1,2,3])
print(pd_val1)
pd_val2=pd_val1
print(pd_val2.dtype) #attribute
print(pd_val2.size) #attribute 
print(pd_val2.name) #attribute returns None
pd_val2.name='counters'
print(pd_val2) #attribute returns counters
#Name of the series becomes column names in dataframes

#we can also give name to index col
print(pd_val2.index.name)
pd_val2.index.name='sr'
print(pd_val2)

print(pd_val2.equals(pd_val1)) #method

In [ ]:
#1. create list of cricketers 
#2. create list of averages
#3. create index as names and avg as values
#4. use dictionary dynamically 

import pandas as pd

cricketers=['sachin','sehwag','virat','dhoni']
averages=[78.7,89.5,83.8,91.2]
#players=pd.Series(averages,cricketers,name='players')
#print(players)
#players=pd.Series({plr:avg for plr,avg in zip(cricketers,averages)},name='players')
#print(players)
players=pd.Series(dict(zip(cricketers,averages)),name='TomTom')
print(players)

In [ ]:
# head() and tail() methods

import pandas as pd

#i_series=pd.Series([item for item in range(51)])
#print(i_series)
i_series=pd.Series(range(51)) # no need of comprehensions
print(i_series)
print(i_series.size,len(i_series)) # len() or size attr gives no of ele
# To explore
print(i_series.head()) # first 5 records
print(i_series.tail()) # last 5 records
print(i_series.head(n=1)) # only first record
print(i_series.tail(n=2)) # only last 2 records
print(pd.Series(range(100))) # will take care of output
#pd.options.display.min_rows=20 
#print(pd.Series(range(100))) # will take care of output first 20 and last 20 records

In [ ]:
# Extracting using index position

from string import ascii_lowercase
from string import ascii_uppercase

import pandas as pd
"""
print(ascii_lowercase)
print(pd.Series(ascii_lowercase))
print(pd.Series(list(ascii_lowercase)))
alphabets=pd.Series(list(ascii_lowercase))
print(alphabets[:3]) # first 3 letters
print(alphabets[-3:]) # last 3 letters
"""
label_alphabet=pd.Series(data=list(ascii_lowercase),index=list(ascii_uppercase))
print(label_alphabet.tail(10))
print(label_alphabet['A'])
label_alphabet=pd.Series(data=list(ascii_lowercase),index=map(lambda chars:'label'+chars,list(ascii_uppercase)))
print(label_alphabet)
print(label_alphabet[0:2]) # index based positioning does not include 2
print(label_alphabet['labelA':'labelC']) # LabelC is included in index based positioning

alphabet=pd.Series(data=list(ascii_lowercase),index=map(lambda chars:'label'+chars,list(ascii_uppercase)))
print(alphabet.add_prefix('mylabel_'))# will not modify alphabet variable
print(alphabet.labelA) # you can use label as an attribute but does not support slicing

In [ ]:
# using loc attribute and boolean masks
# loc is fast and uses labeled based indexing
# 3 ways [] , loc[], get() to access series
import pandas as pd

"""
cities=['mumbai','bengaluru','chennai']
st_series=pd.Series(data=cities,index=['maharashtra','karnataka','tamilnadu'])
print(st_series.loc['maharashtra':'tamilnadu']) 
print(st_series['maharashtra':'tamilnadu'])
print(st_series.get('maharashtra')) # get returns nothing if label is invalid

# Boolean masks are used to index select items at scale
# work with [] and .loc attribute# need to be same length as length of series
# e.g. pd.Series(['A','B','C'][[True,False,True]])
print(st_series.loc[[True,False,True]]) 
# length of the mask must match the len of series else error!
"""

from string import ascii_lowercase
from string import ascii_uppercase

labeled_alphabet=pd.Series(data=list(ascii_lowercase),index=list(ascii_uppercase))
#print(labeled_alphabet)
# we cannot type 26 booleans
#labeled_alphabet.loc[[True,True,True]]
# use list comprehensions
labeled_alphabet.loc[[True for item in range(26)]]
print(labeled_alphabet)
# below line will not work
#labeled_alphabet.loc[[True if item%2==0 else False for item in range(26)]]

# iloc is integer loc and used for indexing by position
# loc is indexing by label 
print(labeled_alphabet.iloc[2]) # c
print(labeled_alphabet.iloc[[2,5,7,9]]) # pass list as an argument
# iloc is used to index rows and columns both in dataframes

In [ ]:
# indexing using callables

import pandas as pd
from string import ascii_lowercase
from string import ascii_uppercase

label_alpha=pd.Series(data=list(ascii_lowercase),index=list(ascii_uppercase))

print(label_alpha.loc[lambda x:[True for x in range(x.size)]])

def every_fifth(item):
    return [True if item%5==0 else False for item in range(item.size)]

print(label_alpha.iloc[lambda item:[True for item in range(item.size)]])
print(label_alpha.iloc[every_fifth])

In [ ]:
# selection by label or selection by position
# 1. series['label'] # slices, callables, boolean masks
# 2. series.loc['label'] # slices, callables, boolean masks
# 2. use series.iloc[position] 
# 3. series.label  # no slice or boolean mask support
# 4. series.get('label') # no slicing but provides default 

import pandas as pd

cities=['mumbai','bengaluru','chennai']
st_series=pd.Series(data=cities,index=['maharashtra','karnataka','tamilnadu'])
print(st_series.loc['maharashtra':'tamilnadu']) 
print(st_series['maharashtra':'tamilnadu'])
print(st_series.get('maharashtra')) # get returns nothing if label is invalid
# get works like loc i.e. labeled indexing and iloc i.e. integer indexing both!
print(st_series.get(1)) # returns bengaluru
print(st_series.get('delhi',default="cannot find value with that label"))
# Here default parameter can take int or dict as values# selection by label or selection by position

In [ ]:
# 1. create a series of length 100 containing squares of ints from 0 to 99 and assign it to variable squares
# 2. Extract the last 3 items from the squares using square bracket indexing
# 3. Repeat the above step using tail() method
# 4. Verify o/p of step2 and step3 is same using equals() method

import pandas as pd

squares=pd.Series(data=[item*item for item in range(100)])
print(squares)
print(squares[-3:])
print(squares.iloc[-3:])
print(squares.get(-3))
print(squares.tail(n=3))
print(squares.tail(n=3).equals(squares[-3:]))

In [ ]:
import pandas as pd
print(pd.read_csv("airports.csv"))

In [ ]:
import pandas as pd
print(pd.read_csv("airports.csv",usecols=["name","type"]))

In [ ]:
import pandas as pd
print(pd.read_csv("airports.csv",usecols=["name","type"],index_col=["type"]))

In [ ]:
import pandas as pd
airports=pd.read_csv("airports.csv",usecols=["name","type"],index_col=["type"])
print(airports.head())

In [ ]:
import pandas as pd
airports=pd.read_csv("airports.csv",usecols=["name","type"],index_col=["type"])
df=airports.head()
print(df)
print(type(df))
print(df)

In [ ]:
import pandas as pd
airports=pd.read_csv("airports.csv",usecols=["name","type"],index_col=["type"])
df=airports.head()
#print(type(airports))
#print(df)
ds=airports.squeeze("columns")
#print(type(ds))
print(ds)

In [ ]:
# attributes of series
import pandas as pd
airports=pd.read_csv("airports.csv",usecols=["name","type"],index_col=["type"])
print(airports.size)
print(airports.index)
print(airports.values)
print(airports.index.size==airports.values.size)

In [ ]:
# .size .shape and len()
import pandas as pd
airports=pd.read_csv("airports.csv",usecols=["name","type"],index_col=["type"])
airports=airports.squeeze(True)
print(airports.shape)
print(airports.shape[0])
print(len(airports))
print(airports.shape[0]==airports.size)

In [ ]:
import pandas as pd
airports=pd.read_csv("airports.csv",usecols=["name","type"],index_col=["type"])
airports=airports.squeeze(True)
print(airports.is_unique)
print(airports.head().is_unique)
print(airports.nunique()) # gives exact count of unique value
print(airports.nunique(dropna=False))

In [ ]:
import pandas as pd

print(pd.Series([1,2,3,3]).is_monotonic)
print(pd.Series([1,2,3,3,1,-1]).is_monotonic)
print(pd.Series([1,2,3,3]).is_monotonic_increasing)
print(pd.Series([5,4,2,1]).is_monotonic)
print(pd.Series([5,4,2,1]).is_monotonic_decreasing)

In [ ]:
import pandas as pd
# count checks only not null values
print(pd.Series([1,2,3,3,4]).count()) 
airports=pd.read_csv("airports.csv",usecols=["gps_code"])  
airports=airports.squeeze(True)
print(airports.count())
print(len(airports))
print(airports.hasnans)

In [ ]:
import pandas as pd

airports=pd.read_csv("airports.csv",usecols=["gps_code"])  
airports=airports.squeeze(True)
airports.isnull()

In [ ]:
#counting null values, non-null values
import pandas as pd

data=pd.read_csv("regions.csv",usecols=['name','intermediate-region-code'],index_col=['name'],squeeze=True)
print("Total records : ",data.size,len(data))
#count() returns only non-Null values
#whereas size attribute returns all values including NaN
print("Non null values: ",data.count())
#hasnans attribute returns True if it has missing values
#print(data.hasnans)
#isnull() returns True/False if NaN
#print(data.isnull())
#use boolean mask or .loc to get NaN
#print(data[data.isnull()])
#print(data.loc[data.isnull()])
#To print only country names use .index
#print(data[data.isnull()].index)
#wrap the country names in a list using ctor
#print(list(data[data.isnull()].index))
#get count of NaN
#print(len(list(data[data.isnull()].index)))
#Here we are isolating nulls, boolean mask, index, list and len of list
print("Nan/null values : ",data.isnull().sum(),data.isna().sum())
#sum() finds sum of boolean True values to get count of null values
#print(sum([True,False,True,False,False])) # returns sum as 2
# method resoultion order 
print(bool.__mro__)
#bool is inherited from class int
print(True+100+False+True+True)# 103 

print("Not null values :",data.notnull().sum(),data.notna().sum())
#count of null and not null values should be equal to size
print(data.isnull().sum()+data.notnull().sum()==data.size)
#print only notnull values
print(data.loc[data.notnull()])

In [ ]:
# dropna() excludes NAs from the series
# fillna() replaces NAs with something else
# both return copy of the series unless inplace=True
import pandas as pd

data=pd.read_csv("cric.csv",usecols=['cricketer','runs'],index_col=['cricketer'],squeeze=True)
print(data.dropna()) # will drop null
print(data) # will not modify series object
#print(data.dropna(inplace=True)) 
#print(data) # will modify series object
print(data.fillna(999,inplace=False))

In [ ]:
# mean median
import pandas as pd

data=pd.read_csv("cric.csv",usecols=['cricketer','runs'],index_col=['cricketer'],squeeze=True)
#average=data.sum()/data.count()
#print(average)
#print(data.mean())
# median is middlemost element in a sorted list of numbers
#print(data.median())
#print(data.quantile(.5))
#print("Mode",data.mode())
# a sorted series containing unique values and their counts
#print("Value counts",data.value_counts())# shows frequency of numbers
# sort=True,ascending=False,dropna=True, normalize=False
#data.hist()
#print(data.describe())# To analyze Series
#print(data.describe(include=float,exclude=object))
#data.filter(regex='^s')
#data.filter(like='i') # filter with index not values
#data[data > 50]# filter by values

# we can do the same using callable
#def fun(dt):
#    return dt>50
#print(data[fun])
#where returns value else string replaced
#data.where(lambda dt:dt>50,other="less than 50")
#data.where(lambda dt:dt>50).dropna()

In [ ]:
# dataframes have 2 dimensions indices, columns
import pandas as pd
import numpy as np
cricketers=['sachin','virat','dhoni','ricky','gayle']
runs=[100,67,88,99,33]
retired=[True,False,False,True,False]
"""
ps=pd.Series(cricketers,name='name')
print(ps)
df=pd.DataFrame({'name':cricketers,'Runs':runs,'status':retired})
print(df)
print(df.iloc[0,0])#row,col
print(df.ndim)
print(df.shape)
print(df.dtypes)
"""
df=pd.DataFrame({'name':cricketers,'Runs':runs,'status':retired})
print(df.info())